# ~/.config/fish/config.fish: DO NOT EDIT -- this file has been generated
# automatically by home-manager.

# Only execute this file once per shell.
set -q __fish_home_manager_config_sourced; and exit
set -g __fish_home_manager_config_sourced 1

source /nix/store/ds1zgkkh0abphva2q3mplqj8n8fyzdmv-hm-session-vars.fish

status is-login; and begin

    # Login shell initialisation

end

status is-interactive; and begin

    # Abbreviations
    abbr --add -- db devbox
    abbr --add -- dbs 'devbox shell'
    abbr --add -- ga 'git add'
    abbr --add -- gc 'git commit -m'
    abbr --add -- gp 'git push'
    abbr --add -- nr 'nix run nixpkgs#home-manager -- switch --flake .'
    abbr --add -- nu 'nix flake update && nix run nixpkgs#home-manager -- switch && nix-store --gc'

    # Aliases
    alias cat bat
    alias eza 'eza --icons auto --git --hyperlink --group-directories-first --header'
    alias glow 'glow --pager'
    alias ip 'ip --color --brief'
    alias la 'eza -a'
    alias less 'bat --paging=always'
    alias lg lazygit
    alias ll 'eza -l'
    alias lla 'eza -la'
    alias ls eza
    alias lt 'eza --tree'
    alias man batman
    alias more 'bat --paging=always'
    alias tree 'exa --tree --group-directories-first'
    alias update-clean 'nix flake update && nix-store --gc'
    alias vim nvim
    alias vimdiff 'nvim -d'
    alias wget wget2

    # Interactive shell initialisation
    # Customize "pure" colors and options
    set -g pure_color_current_directory brcyan
    set -g pure_color_mute yellow

    set --universal pure_symbol_virtualenv_prefix "" # 🐍
    set --universal pure_color_virtualenv green

    fish_add_path ~/.local/bin

    # Enable VI key bindings
    if test -n "$TERM"
        fish_vi_key_bindings
        set -g fish_cursor_default block blink
        set -g fish_cursor_insert line blink
        set -g fish_cursor_replace_one underscore blink
        set -g fish_cursor_visual block
    end

    # Sponge plugin config
    set sponge_delay 5

    # Ayu Mirage theme. Dumped with
    # fish_config theme dump "ayu Mirage" > ayu_mirage.fish
    set -g fish_color_autosuggestion 6c7086
    set -g fish_color_cancel f38ba8
    set -g fish_color_command 89b4fa
    set -g fish_color_comment 7f849c
    set -g fish_color_cwd f9e2af
    set -g fish_color_cwd_root red
    set -g fish_color_end fab387
    set -g fish_color_error f38ba8
    set -g fish_color_escape eba0ac
    set -g fish_color_gray 6c7086
    set -g fish_color_history_current --bold
    set -g fish_color_host 89b4fa
    set -g fish_color_host_remote a6e3a1
    set -g fish_color_keyword f38ba8
    set -g fish_color_match F07171
    set -g fish_color_normal cdd6f4
    set -g fish_color_operator f5c2e7
    set -g fish_color_option a6e3a1
    set -g fish_color_param f2cdcd
    set -g fish_color_quote a6e3a1
    set -g fish_color_redirection f5c2e7
    set -g fish_color_search_match --background=313244
    set -g fish_color_selection --background=313244
    set -g fish_color_status f38ba8
    set -g fish_color_user 94e2d5
    set -g fish_color_valid_path --underline
    set -g fish_pager_color_background
    set -g fish_pager_color_completion cdd6f4
    set -g fish_pager_color_description 6c7086
    set -g fish_pager_color_prefix f5c2e7
    set -g fish_pager_color_progress 6c7086
    set -g fish_pager_color_secondary_background
    set -g fish_pager_color_secondary_completion
    set -g fish_pager_color_secondary_description
    set -g fish_pager_color_secondary_prefix
    set -g fish_pager_color_selected_background
    set -g fish_pager_color_selected_completion
    set -g fish_pager_color_selected_description
    set -g fish_pager_color_selected_prefix

    set -g SHELL /nix/store/rw4a9sbj68w9qyh55j2k6c56jmw7yjxx-fish-4.0.1/bin/fish
    fish_add_path ~/bin

    if test "$TERM" != dumb
        /home/manolo/.nix-profile/bin/starship init fish | source

    end

    # add completions generated by Home Manager to $fish_complete_path
    begin
        set -l joined (string join " " $fish_complete_path)
        set -l prev_joined (string replace --regex "[^\s]*generated_completions.*" "" $joined)
        set -l post_joined (string replace $prev_joined "" $joined)
        set -l prev (string split " " (string trim $prev_joined))
        set -l post (string split " " (string trim $post_joined))
        set fish_complete_path $prev "/home/manolo/.local/share/fish/home-manager_generated_completions" $post
    end

    /nix/store/a2f68ipvpd810x3cnsk9i1jzzsx6f01s-direnv-2.35.0/bin/direnv hook fish | source

end
